import localFont from 'next/font/local';
import { Nanum_Gothic_Coding } from 'next/font/google';
import './globals.css';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};
const nanum_Gothic = Nanum_Gothic_Coding({ subsets: ['latin'], weight: ['400'] });

// const youth = localFont({ src: '../public/fonts/Youth.ttf' });
export default function RootLayout({ children }) {
	return (
		<html lang='ko'>
			<head>
				<link rel='manifest' href='/manifest.json' />
			</head>
			<body className={nanum_Gothic.className}>{children}</body>
			{/* <body>{children}</body> */}
		</html>
	);
}
