import { Noto_Sans_KR } from 'next/font/google';
import './globals.css';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};
const notosansFont = Noto_Sans_KR({
	subsets: ['latin'],
	weight: ['100', '300', '400', '500', '700', '900'],
});

export default function RootLayout({ children }) {
	return (
		<html lang='ko'>
			<head></head>
			<body className={notosansFont.className}>{children}</body>
		</html>
	);
}
